### ISSUE TITLE
Something wrong with Bootstrap CDNs

### ISSUE THREAD

**Issue by awangg** [waytab/WayTab#17]
Bootstrap is very clearly not working on Waytab. I think it's something wrong with the CDNs. It won't even load for me right now so...

**Comment by awangg** [comment]
![waytab bootstrap ded 1](https://user-images.githubusercontent.com/26381500/44245252-dc26b480-a1a5-11e8-94ea-d6340152faec.png)
![waytab bootstrap ded 2](https://user-images.githubusercontent.com/26381500/44245253-dc26b480-a1a5-11e8-915d-a4a3d9bb4349.png)
![waytab bootstrap ded 3](https://user-images.githubusercontent.com/26381500/44245254-dc26b480-a1a5-11e8-998a-ca3de6adf9c2.png)
![waytab bootstrap ded 4](https://user-images.githubusercontent.com/26381500/44245255-dc26b480-a1a5-11e8-9c8c-dbf9c57752ec.png)

**Comment by andrewward2001** [comment]
Just go to the bootstrap website and copy the CSS tags from there and replace the ones we've got right now

**Comment by awangg** [comment]
@andrewward2001 i was thinking to just make local copies of the files, like having our own bootstrap.min.css and stuff

**Comment by awangg** [comment]
Just did it even though it was fixed: https://github.com/waytab/WayTab/commit/dd6d576a20aca2c3cf7cf996e265f60a179842b4
