### ISSUE TITLE
Use moment.js for timebar

### ISSUE THREAD

**Issue by andrewward2001** [waytab/WayTab#18]
There's a really handy library called [moment.js](http://momentjs.com/) for working with time and all that. It's a lot more robust than the native JS Date class and will automagically update the time. @awangg this is more your department but I think time.js can really be cleaned up if rewritten with moment.

**Comment by awangg** [comment]
Sounds good, I'll start working on it.

**Comment by andrewward2001** [comment]
Done by @awangg , see https://github.com/waytab/WayTab/commit/eec7eb0eb48df5da543be272884baa8ec0e8a0bb
