### ISSUE TITLE
Dynamically label the "Add Current Tab" dialog

### ISSUE THREAD

**Issue by andrewward2001** [waytab/WayTab#19]
Instead of the button just saying "Add Current Tab", it could say "Add ${title}", i.e. "Add GitHub" or "Add Homepage - Material Design"

**Comment by awangg** [comment]
Yeah this is definitely better than the current system. We can probably make improvements to it anyway, it's extremely bare-bones and the functionality is iffy -- as demonstrated by #15

**Comment by andrewward2001** [comment]
Done -- see https://github.com/waytab/WayTab/commit/d94c9533f044aa28fa944bdf3ef6ae4cd3aa7c61
