### ISSUE TITLE
Unable to modify links

### ISSUE THREAD

**Issue by mikehopps** [waytab/WayTab#21]
**Describe the bug**
I cannot edit the textfields in the links tab in settings.

![image](https://user-images.githubusercontent.com/4509544/45033762-80707e00-b023-11e8-9617-752d1db3235a.png)

**Comment by awangg** [comment]
@mikehopps I literally cannot reproduce our bug lol

**Comment by andrewward2001** [comment]
Same, fresh install of WayTab and I can't reproduce this.
