### ISSUE TITLE
Block schedule not highlighting

### ISSUE THREAD

**Issue by awangg** [waytab/WayTab#22]
Blocks are not highlighting correctly, or at all. I anticipate that this is because of the updated website, which looks like absolute butt

**Comment by andrewward2001** [comment]
With the new website, they're using a new Google calendar to replace the old system. The new calendar offers some new challenges to getting the correct letter day, but it's still not very difficult. The calendar is [here](https://calendar.google.com/calendar/embed?showTz=0&mode=AGENDA&src=wayland.k12.ma.us_vhri0sqonn3vcmis02v9bct64o%40group.calendar.google.com&color=%2342104A&src=wayland.k12.ma.us_hdhmk89bcnj0te0g7ptofr8ulo%40group.calendar.google.com&color=%23865A5A&ctz=America%2FNew_York). A given day can be found with `#day-[year][mo][date]`, i.e. `#day-20180907`. Within each day are various `.event`s, which we only need the one of that has a single character.

**Comment by andrewward2001** [comment]
See https://github.com/waytab/WayTab/commit/b447198847402b011168ec6fe53b448d126ea783 for the beginnings of the fix, but unfortunately jQuery isn't playing nice for some reason. Will have to investigate. The pieces are there, though.

**Comment by andrewward2001** [comment]
This doesn't appear to be fixable, due to the way Google Calendar handles things. I'm closing this issue for now, but we can revisit this in the future.
