### ISSUE TITLE
Randomly can't get rid of assignments

### ISSUE THREAD

**Issue by TimmyKwan** [waytab/WayTab#25]
**Is your feature request related to a problem? Please describe.**
actually is equivalent to eating diarrhea ass

**Describe the solution you'd like**
idek be better

**Describe alternatives you've considered**
dont eat ass

**Additional context**
fix the rats nest

**Comment by TimmyKwan** [comment]
broke again
![screen shot 2018-09-13 at 6 16 54 pm](https://user-images.githubusercontent.com/32459174/45518973-4f115400-b781-11e8-8ea1-ea09235fb5d6.png)

**Comment by awangg** [comment]
@TimmyKwan https://github.com/waytab/WayTab/commit/1b390704558a4a9d975370a26a56cb8d53cf675f added a force reset button that can help you
