### ISSUE TITLE
Bro what is this

### ISSUE THREAD

**Issue by TimmyKwan** [waytab/WayTab#28]
![screen shot 2018-09-13 at 2 43 33 pm](https://user-images.githubusercontent.com/32459174/45508759-aa344e00-b763-11e8-81cb-b80d130b8cc0.png)

**Comment by awangg** [comment]
you didn't define a due date idiot

**Comment by TimmyKwan** [comment]
@awangg i dont need to define a due date, this just happened when it updated

**Comment by awangg** [comment]
@TimmyKwan loser
