### ISSUE TITLE
Default Todo Selector to Misc.

### ISSUE THREAD

**Issue by awangg** [waytab/WayTab#31]
self-explanatory

**Comment by andrewward2001** [comment]
I actually silently did this already https://github.com/waytab/WayTab/commit/0910c748f0504aa4a67d8f9486f9da4a634eefef

**Comment by awangg** [comment]
fixed it again in https://github.com/waytab/WayTab/commit/df0db511bf73a148bfd00f7aadcaa206ba1cb5a4
