### ISSUE TITLE
Add "custom" classes

### ISSUE THREAD

**Issue by awangg** [waytab/WayTab#34]
Todo should have a feature (probs in late 1.1.x or 2.0 even) where you can add manually add a "custom" class. By that I mean like for people with extracurriculars, they should be able to add like a debate team or student government "class" so they don't have to put all of their non-academic assignments under misc. and have it all jumbled.

**Comment by awangg** [comment]
done in https://github.com/waytab/WayTab/commit/03fe5793582152e8830b59c29f021c814dfc55b8

lmao no plagiarism at all

**Comment by andrewward2001** [comment]
wow looks familiar...

**Comment by awangg** [comment]
nope no plagiarism at all
