### ISSUE TITLE
Time 

### ISSUE THREAD

**Issue by Rayonthecrayon** [waytab/WayTab#41]
**Describe the bug**
The block percent goes over 100 so you don't know when the class has actually started or how long its gone too. Unless you reload. 
**To Reproduce**
1. Go to '.Waytab..'
Wait for the block to get to 100% and see it go to 101 and higher

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by awangg** [comment]
Thanks! Will fix in 1.1.2

**Comment by awangg** [comment]
Actually, we released 1.1.1 today, I think that [this](https://github.com/waytab/WayTab/commit/129814c275d82a99aa9e6d96811d0a2c1126fc26) might've fixed it.

**Comment by awangg** [comment]
Gonna close for now...feel free to reopen if https://github.com/waytab/WayTab/commit/129814c275d82a99aa9e6d96811d0a2c1126fc26 wasn't the fix you were looking for.
