### ISSUE TITLE
Can't remove tasks

### ISSUE THREAD

**Issue by andrewward2001** [waytab/WayTab#42]
When clicking the checkbox, tasks stay there. Error in console.

We are aware of this bug. Please don't make a new issue.

See https://github.com/waytab/WayTab/blob/master/page/js/todo.js#L167 col 72 for exact *missing period*. That's literally the entire problem.

**Comment by awangg** [comment]
@andrewward2001 should we push out an emergency update on this one?

**Comment by awangg** [comment]
Solved in https://github.com/waytab/WayTab/pull/43
