### ISSUE TITLE
Undo problem

### ISSUE THREAD

**Issue by awangg** [waytab/WayTab#44]
The undo button only restores the first section of the task (i.e. the first two parts of the array I think).
Afterwards trying to delete the task results in this:
![screen shot 2018-10-01 at 10 27 45 pm](https://user-images.githubusercontent.com/26381500/46326123-5a5ddf80-c5c9-11e8-9e15-0cc739a81dd1.png)

**Comment by awangg** [comment]
@andrewward2001

**Comment by andrewward2001** [comment]
I'm not having this problem

**Comment by awangg** [comment]
turns out its an old problem

**Comment by awangg** [comment]
fixed in https://github.com/waytab/WayTab/commit/233213cc4f94f3d51263c8b3dd2e8fc3d4c5620e but ward was too lazee to say this
