### ISSUE TITLE
bring back letter days

### ISSUE THREAD

**Issue by awangg** [waytab/WayTab#48]
i think this might work to bring back letter day integration
https://developers.google.com/calendar/

the calendar api can let us retrieve stuff from public google calendars. and the school calendar can be found here: https://calendar.google.com/calendar/embed?title=WHS%20and%20District%20Events&showDate=0&showPrint=0&showTz=0&mode=AGENDA&height=600&wkst=1&bgcolor=%23FFFFFF&src=wayland.k12.ma.us_vhri0sqonn3vcmis02v9bct64o%40group.calendar.google.com&color=%2342104A&src=wayland.k12.ma.us_hdhmk89bcnj0te0g7ptofr8ulo%40group.calendar.google.com&color=%23865A5A&ctz=America%2FNew_York

the link is long cuz it's an embedded thing for the whs site, but if we can find a way to get the actual calendar, then we might be able to use the API to bring back the letter days.

**Comment by andrewward2001** [comment]
the js API requires oauth

**Comment by andrewward2001** [comment]
also the url can be shortened to https://calendar.google.com/calendar/embed?src=wayland.k12.ma.us_hdhmk89bcnj0te0g7ptofr8ulo%40group.calendar.google.com

**Comment by awangg** [comment]
booo oauth
