### ISSUE TITLE
Split block four into lunch blocks in the time bar

### ISSUE THREAD

**Issue by awangg** [waytab/WayTab#50]
Self explanatory

**Comment by awangg** [comment]
Done in https://github.com/waytab/WayTab/commit/21970785f5b34655b6b77631ac174500a2972cc8

**Comment by andrewward2001** [comment]
oof

**Comment by awangg** [comment]
@andrewward2001 what u wang

**Comment by andrewward2001** [comment]
"what u wang" ~ Andeth Want, 2018
