### ISSUE TITLE
"load more" option in the WSPN rss feed

### ISSUE THREAD

**Issue by awangg** [waytab/WayTab#53]
add a button to the bottom so you can load five more articles in the wspn rss feed

**Comment by awangg** [comment]
rss*

**Comment by andrewward2001** [comment]
Fucking autocorrect

**Comment by awangg** [comment]
and you're false, it's 10 items in the rss feed
waylandstudentpress.com/feed and cmd+f "item"

**Comment by awangg** [comment]
wait im actually stupid

**Comment by andrewward2001** [comment]
There are closing tags

**Comment by awangg** [comment]
i know, im stupid
