### ISSUE TITLE
Custom classes thingy breaks when there's no schedule

### ISSUE THREAD

**Issue by andrewward2001** [waytab/WayTab#54]
[yep](https://www.youtube.com/watch?v=WC9rDR0gsHE), so if you're working with a [fresh](https://youtu.be/sTJ1XwGDcA4?t=51) [install](https://www.youtube.com/watch?v=AFxd1vH4Q5U) of [baetab for budents](https://www.youtube.com/watch?v=ydk_pc-jx1c), and you [head ](https://www.youtube.com/watch?v=cffSbDucnrM)into the classes tab of the settings, it'll just be totally blank save for the title.
![untitled](https://user-images.githubusercontent.com/3325089/46973238-a19aa480-d08e-11e8-8bc4-68a5a3575f9a.png)

**Comment by andrewward2001** [comment]
also click on "install" thats a great one

**Comment by awangg** [comment]
yeah cuz u dont have any classes? did the fresh install have a schedule saved

**Comment by andrewward2001** [comment]
well, no, but i dont see why i can't still add a custom class or why the entire section is blank, despite the tab existing and the heading as well.

**Comment by awangg** [comment]
oooooooooooooh oopsie badoopsie i thought you meant that there should be classes showing up. yeah it's a quicc ficc

**Comment by andrewward2001** [comment]
ok so after your latest commit i didn't work for me
![untitled](https://user-images.githubusercontent.com/3325089/47112903-99c13880-d225-11e8-8c12-99297a19f620.png)

**Comment by awangg** [comment]
ye i gotchu, i'll ficc it l8r

**Comment by andrewward2001** [comment]
seems to work now, but the add button shows up at the top of the list

**Comment by andrewward2001** [comment]
should be fixed https://github.com/waytab/WayTab/commit/d5d1957f76f6cfa54c0762e9d83aaca0084c7af1
