### ISSUE TITLE
special schedule json format is wrong

### ISSUE THREAD

**Issue by awangg** [waytab/WayTab#65]
@andrewward2001 you thought it ended with the comma. it didn't. just some minor things though.
1. there should be a "length" property in each of the time blocks denoted in the "schedule" property of the json which is basically just the difference between the end time and start time in minutes.
2. on specified day of, the special schedule becomes a "past schedule", meaning that when I try to access it using the URL, I get the 1969 thing (or the next schedule) cuz the actual schedule apparently passed. it's probably an issue with the unix timestamp, maybe make the timestamp based on the actual date instead, like how moment formats it (YYYY-MM-DD)?
3. the actual bell-schedule in our config.json, which our time.js file is really built for, differentiates between bell 1, 2, 3, and 4 (weekend) schedules as like subarrays. this one doesn't, so the getCurrentBlock() function in time.js gets confused af. should fix, you could probably copy the getTodaySchedule() function in time.js to create the subproperty.

otherwise it's all yeeti

**Comment by andrewward2001** [comment]
this issue should be on the repo for manage. but anyway, the third point isn't an issue with manage and should be fixed in waytab. I'm not putting it in manage. I think the second thing was fixed (?) but changing how dates are stored isn't super viable since timestamps tend to be pretty robust. and also doesn't moment have the ability to get time differences?

**Comment by awangg** [comment]
@andrewward2001 alright I moved it, but should we change the format in WayTab or should we just have it match in manage?

**Comment by andrewward2001** [comment]
I think it makes sense to assign the schedule number or whatever based on whether there's a special schedule in the first place cause it doesn't make a ton of sense to me to put that in the ajax thingy.
