### ISSUE TITLE
Setup process

### ISSUE THREAD

**Issue by andrewward2001** [waytab/WayTab#7]
After installation and first run, users should be brought through a setup process to populate WayTab with data immediately. Some info we want to collect (to be stored on the user's browser):
* Name
* Basic preferences (bg option, font, etc)
* Schedule

We might also want to provide an overview of how to use WayTab.

**Comment by awangg** [comment]
sooooooooooooooœ
will this ever actually hapen

**Comment by andrewward2001** [comment]
https://github.com/waytab/WayTab/commit/a02881d5bf9b4c7f6e1ef089053873d9c10ef76a
https://github.com/waytab/WayTab/commit/2dbd2e698e4f5557b3e09a1cc3de52f12ef9f16c
https://github.com/waytab/WayTab/commit/441bddb4675275a5c230745fe7e0ec61346f8a0d
https://github.com/waytab/WayTab/commit/d67cd325bef1913c9f360095f3262cea3bb11705
https://github.com/waytab/WayTab/commit/8707cb3566270fb6c35ab87a7ac7fdfa02718be4
https://github.com/waytab/WayTab/commit/ea1f07158900c2646f7063752f476af80ce76dd8
https://github.com/waytab/WayTab/commit/b5b8eb8dd17d49d6c35a3246b80f9b8ea7ca59d5
https://github.com/waytab/WayTab/commit/b66137ec554e7851ba1e6828fc300544b3586b79
https://github.com/waytab/WayTab/commit/685722afd2bd292fd4fba7744f8d1c1ccbd6dd12
https://github.com/waytab/WayTab/commit/fd0985e863a9408ab599f00e48103ff44dfa7ffe
https://github.com/waytab/WayTab/commit/0a6699501b718ba5d9bfa7890c16be00206f5ecf
https://github.com/waytab/WayTab/commit/6454d9f5581b98c3a5548d97ee0543b2aa2ca493
https://github.com/waytab/WayTab/commit/d065b03aaa13cd14576a906ac515ab08b80ab4c8

**Comment by awangg** [comment]
yeeti yeeti yeeti

**Comment by andrewward2001** [comment]
https://github.com/waytab/WayTab/commit/44207622d0a57b42eda409cbe0741f3b327dd3b7
https://github.com/waytab/WayTab/commit/f1af9a20278306b7db87284ae625f9e9e73e9158
https://github.com/waytab/WayTab/commit/cf0ad81b8728be77917939f6a057fd250b44ad26
https://github.com/waytab/WayTab/commit/9dbf7c4831a3f2188af0ea8519a14c552074a8f6

**Comment by andrewward2001** [comment]
Done. needs testing  
see https://github.com/waytab/WayTab/commit/44b12bcdd6a7cfb1f6cd9d54b14d34406eb1e0e0

**Comment by awangg** [comment]
just tested, looks really good. a few things
1) can we implement the same highlighting used in the setup process into the regular schedule editor? it's actually big helpful.
2) it looks like people who already have waytab will go through the setup process. but for me it reset my schedule, tasks, and personalization stuff. i chose to go through the tutorial, would it be different if i skipped?
3) for the settings button at the bottom, clicking like "personalize" or "about" on the drop-up doesn't actually open the modal, only general does.

**Comment by andrewward2001** [comment]
ok so
1. this is a separate issue, and I do plan to do this, yes
2. yep, so hitting skip won't erase your settings, but I can add a thing so setup won't run in the first place
3. also a separate issue, but that's just me being _LAZY_ and i _suppose_ i'll fix that soon

**Comment by awangg** [comment]
1. k
2. k
3. lmao i just noticed cuz i was sifting thru the code and noticed u only added the data-toggle stuff for general

**Comment by andrewward2001** [comment]
yeah cause ill probs split those into separate modals and that's a pain in the arse so im putting it off

**Comment by andrewward2001** [comment]
https://github.com/waytab/WayTab/commit/32f908206c4719ea973c86addb55c5948837b928
mmmmk so that finishes this issue but it needs testing to make sure it's production-ready (pretty sure it is though; i write fire code)

**Comment by awangg** [comment]
nice it only took you half a year
