### ISSUE TITLE
Due dates collide with existing features

### ISSUE THREAD

**Issue by awangg** [waytab/WayTab#8]
I implemented due dates in 1.0.2, but it changes the structure of how we keep track of tasks. Now, tasks for each classes are stored in a 2D array where each index is an array with the task name and the due date, ex: ["Math Packet", "7/18/2018"].

Merging this version with version 1.0.1 will cause problems as two different storage types are used. Need to figure out a way to account for the previous version.

**Comment by andrewward2001** [comment]
This is something where both data structures can be used but will need to be checked for in code, so we can check if it's a string or an array. Also, this feels more like a 1.1 feature...?

**Comment by awangg** [comment]
I thought that since this was easier to implement, it was fine for a 1.0.2 feature. We can change this to 1.1 if you want, cause I feel like right now it's causing more problems than it should.

**Comment by awangg** [comment]
Tentative Fix. See 655823665c9f0e146cd64d17543538a5d799204e
