### ISSUE TITLE
ur bad wang

### ISSUE THREAD

**Issue by minglethepringle** [waytab/WayTab#81]
**Describe the bug**
Day schedule does not update when you select a new letter day.

**To Reproduce**
1. Click View Grid
2. Select a different letter day than you're on now
3. Click View Day
4. Voila wrong schedule

**Expected behavior**
The right schedule to show up

**Screenshots**
![screen shot 2019-03-05 at 7 32 56 am](https://user-images.githubusercontent.com/16504328/53813111-e4202900-3f2a-11e9-91c5-95f4f2fa9162.png)
![screen shot 2019-03-05 at 7 33 04 am](https://user-images.githubusercontent.com/16504328/53813120-e8e4dd00-3f2a-11e9-9226-af8d65933a8c.png)

**Additional context**

**Comment by awangg** [comment]
That’s on @andrewward2001 
I didnt work on this

**Comment by awangg** [comment]
Alternatively, you can channel some problem solving skills and just reload the page.

**Comment by andrewward2001** [comment]
this is a feature.

**Comment by minglethepringle** [comment]
i could reload the page....or wartardo could fix this

**Comment by andrewward2001** [comment]
or you could open a pr and fix this yourself

**Comment by minglethepringle** [comment]
nah
