### ISSUE TITLE
Due dates should accomodate MM/DD/YYYY format

### ISSUE THREAD

**Issue by awangg** [waytab/WayTab#9]
Due dates can only take the raw date right now, meaning that to plug in February 2nd, 1971 you have to do 2/2/1971. Should make it so that you can input 02/02/1971 as an equivalent to 2/2/1971.

**Comment by andrewward2001** [comment]
You can change the date input from type `text` to `date`, which will both enforce the format, but will also make it so Chrome will display a calendar to select a date.  
https://www.w3schools.com/tags/att_input_type_date.asp

**Comment by awangg** [comment]
Alright that sounds good

**Comment by awangg** [comment]
I'll undo my commit and reformat
